### ISSUE TITLE
ChefSpec 3.1.1. does not work with i18n 0.6.5.

### ISSUE THREAD

**Issue by DracoAter** [sethvargo/chefspec#289]
Showed this error, when tried:

```
/var/lib/gems/1.9.1/gems/chefspec-3.1.1/lib/chefspec.rb:51:in `<top (required)>': undefined method `enforce_available_locales=' for I18n:Module (NoMethodError)
```

Updating i18n to 0.6.9 helped. (Didn't try it with any version in between). I guess you should update the dependencies.

i18n ~> 0.6 is not enough
