### ISSUE TITLE
undefined method `__rspec_original_dup' for class `Chef::Recipe' after upgrade to 0.7.0

### ISSUE THREAD

**Issue by jimhopp** [sethvargo/chefspec#44]
Hi guys-

Here's a snippet of a failure running a test after I upgraded to 0.7.0. (The only change I made was to update the Gemfile to specify 0.7.0 for chefspec):
  318) virtualbox::default should not download the virtualbox image if a url is not set
     Failure/Error: Unable to find matching line from backtrace
     NameError:
       undefined method `__rspec_original_dup' for class`Chef::Recipe'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/any_instance.rb:73:in `alias_method'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/any_instance.rb:73:in`restore_dup'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/any_instance.rb:72:in `class_eval'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/any_instance.rb:72:in`restore_dup'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/any_instance.rb:46:in `rspec_reset'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/space.rb:17:in`reset_all'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/space.rb:16:in `each'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks/space.rb:16:in`reset_all'
     # /Library/Ruby/Gems/1.8/gems/rspec-mocks-2.11.2/lib/rspec/mocks.rb:23:in `teardown'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/mocking/with_rspec.rb:18:in`teardown_mocks_for_rspec'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:308:in `run_after_each'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:119:in`run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:253:in `with_around_each_hooks'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:110:in`run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:378:in `run_examples'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in`map'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `run_examples'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:360:in`run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in`map'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/reporter.rb:34:in`report'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:25:in `run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in`run'
     # /Library/Ruby/Gems/1.8/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `autorun'
     # /Library/Ruby/Gems/1.8/bin/rspec:23

If you want to try to reproduce this, I also get the error when I upgraded my demo repo at https://github.com/jimhopp/chefspec_exploration.

Any guidance>
